version: '3'
services:
  league-simulation:
    container_name: league-simulation
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/var/www/html
    depends_on:
      - db-dev
  db-dev:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: league_simulation_db
      MYSQL_USER: league-user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data2:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db-dev
      MYSQL_ROOT_PASSWORD: root
volumes:
  db_data2:
